### ISSUE TITLE
How to bundle it?

### ISSUE THREAD

**Issue by kacperpaczos** [react-gjs/react-gjs-renderer#222]
I try to configure all of three recommended bundlers in README, but i have always some errors. 
For example: 
`Could not resolve "gi://Gdk"`

**Comment by ncpa0cpl** [comment]
If you are using a bundler you will have to configure it to not bundle the "gi://" imports. I know that in esbuild you can mark imports as "external" via a [config option](https://esbuild.github.io/api/#external) or via plugins. I do not know how to do that in other bundlers.

Alternatively you could use [this build tool](https://github.com/react-gjs/react-gnome/) I've created specifically for building react for gjs.

**Comment by kacperpaczos** [comment]
I don't see instruction how to use it,can you explain this for me?

PS: czy jest sens pisać tu i po angielsku? Jeśli ten projekt ma kanał na matrix to chętnie się dołącze.

**Comment by kacperpaczos** [comment]
Also: I tried using this script, same result.
`"bundle": "esbuild ./src/index.ts --bundle --platform=node --outfile=./dist/dupa.js --external:gi://Gdk?version=3.0 --external:gi://Gtk?version=3.0 --external:gi://Gio --external:gi://Gtk --external:system",`

**Comment by ncpa0cpl** [comment]
You can use a `*` token to match all imports starting with `gi://`. Something like that: `esbuild  ./index.ts "--external:gi://*"`. If this doesn't work I'd suggest using the esbuild's node binding to write a build script like this example (taken from esbuild docs):

```js
import * as esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['app.jsx'],
  bundle: true,
  outfile: 'out.js',
})
```

If the imports are correctly marked as external you definitely shouldn't get that error.

**Comment by kacperpaczos** [comment]
So I have: 
`"bundle": "rm -rf ./dist && rm -rf ./bundled && tsc && esbuild ./dist/index.js --bundle '--external:gi://*' --external:system --outfile=./bundled/react-gjs-renderer.js",`

This is a bundled project, but is this the right way to create a bundled version and use it in your applications?
