### ISSUE TITLE
How to run example app?

### ISSUE THREAD

**Issue by kacperpaczos** [react-gjs/react-gjs-renderer#223]
I have code in app.tsx:
```
import { Box, Label, Window, exit, render } from "../bundled/react-gjs-renderer";

const App = () => (
  <Window onDestroy={exit}>
    <Box>
      <Label>Hello World!</Label>
    </Box>
  </Window>
);

render(<App />);
```

I have included react-gjs renderer: #222

I can't run this via cjs/gjs because I have errors:
```
(gjs:622742): Gjs-CRITICAL **: 23:27:40.683: JS ERROR: SyntaxError: import declarations may only appear at top level of a module @ app/app.tsx:1:0

(gjs:622742): Gjs-CRITICAL **: 23:27:40.684: Script app/app.tsx threw an exception
```

**Comment by ncpa0cpl** [comment]
So first things first, that example from README is a little bit outdated, it should look something more like this:

```tsx
import Gtk from "gi://Gtk?version=3.0";
import * as React from "react";
import { Box, Label, render, Window } from "./src/index.ts";

Gtk.init(null);

const App = () => {
  return (
    <Window
      quitAppOnClose
      minWidth={200}
      minHeight={200}
    >
      <Box>
        <Label>Hello World</Label>
      </Box>
    </Window>
  );
};

render(<App />, {
  appId: "com.example.app",
});

imports.mainloop.run();

```

Also I think you misunderstood that thing about bundling, what I am recommending is to bundle the application not the library, in other words if the above example is inside a `App.tsx` file, then you should run this command to bundle it:
```  esbuild ./App.tsx --bundle '--external:gi://*' --external:system  --format=esm --outfile=./out.js ```
And this is assuming that `react-gjs-renderer` is inside the node_modules directory.

I've just tried exactly this setup and executing `gjs -m ./out.js` works as expected, a window with a "hello world" message appears.

**Comment by ncpa0cpl** [comment]
I have no idea how the shell extensions differ from regular desktop apps, and what you'd need to do to make it work. I am guessing that a shell extension doesn't use `Gtk.Application`, and probably you don't create a window for them either, so a separate `render()` function would be needed, one that doesn't initiate a new `Gtk.Application`, if that's all then I would see no problem adding support for that.

**Comment by kacperpaczos** [comment]
Ok, i will think about it later, now, did i can create my own component with my own logic and style like in the web app?
